[package]
name = "api_gateway"
edition = "2024"
version.workspace = true
authors.workspace = true

[dependencies]
axum.workspace = true
tokio.workspace = true
tower.workspace = true
tower-sessions.workspace = true

auth = { path = "../auth" }