[package]
name = "source_validation"
edition = "2024"
version.workspace = true
authors.workspace = true

[dependencies]
reqwest.workspace = true
serde_json.workspace = true

shared = { path = "../shared" }
